---

# rh-base
rhbase_user_groups:
  - management
  - technical
  - sales
  - it
  - public

# Zet gewone users in all.yml


# samba

samba_netbios_name: FILES
samba_workgroup: AVALON
samba_wins_support: true
samba_load_homes: true
samba_load_printers: false
samba_create_varwww_symlinks: true
samba_log: /var/log/samba.log

samba_users:
  - name: stevenh
    password: hnevets
  - name: stevenv
    password: vnevets
  - name: leend
    password: dneel
  - name: svena
    password: anevs
  - name: nehirb
    password: brihen
  - name: alexanderd
    password: drednaxela
  - name: krisv
    password: vsirk
  - name: benoitp
    password: ptioneb
  - name: anc
    password: cna
  - name: elenaa
    password: aanele
  - name: evyt
    password: tyve
  - name: christophev
    password: vehpotsirhc
  - name: stefaanv
    password: vnaafets
  - name: robin
    password: testpassword

samba_shares_root: /srv/shares # pas naam aan adhv testscript


samba_shares:
  - name: management
    group: management
    write_list: +management

  - name: public
    group: public
    write_list: +public
    public: yes
    setype: public_content_t

