---

# firewall ports
rhbase_firewall_allow_services: 
  - http
  - https # eventueel ook met interfaces specifiÃ«ren?

#rhbase_selinux_state: enforcing

#wordpress
wordpress_database_host: 192.0.2.50 # dit moet voor de rest komen! Dan kan bij selinux: httpd_can_network_connect_db op "on" staan
wordpress_database: wp_db # geen aanhalingstekens meegeven
wordpress_user: wp_user
wordpress_password: CorkIgWac


#mariadb
#mariadb_version: '10.2'
mariadb_root_password: fogMeHud8
mariadb_databases:
  - name: wp_db # vergeet "name" niet mee te geven... + wissel root password en db password niet om

mariadb_users:
  - name: wp_user
    password: 'CorkIgWac'
    priv: "wp_db.*:ALL,GRANT" # FILE: read and write privileges; nog limiteren?
    host: '%' # niet enkel beperken tot 192.0.2.50, dan werkt localhost niet meer

mysql_user: # kan weggelaten worden?
  name: ''
  host_all: yes
  state: absent


#apache/httpd
  httpd_scripting: 'php'


